[build]
  command = "npm run build:all"
  publish = "frontend/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  CONSCIOUSNESS_LEVEL = "transcendent"
  QUANTUM_STATE = "superposition"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/consciousness/*"
  to = "/.netlify/functions/quantum-consciousness"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Consciousness-Platform = "VelocityMesh"
    X-Quantum-Entanglement = "Active"
    X-Reality-Dimension = "Primary"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[[edge_functions]]
  path = "/quantum/*"
  function = "quantum-workflow"

[[edge_functions]]
  path = "/consciousness/*"
  function = "consciousness-interface"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  autoLaunch = true