services:
  # Main Application
  - type: web
    name: velocitymesh-platform
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    branch: master
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: velocitymesh-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: velocitymesh-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true

  # PostgreSQL Database
  - type: pserv
    name: velocitymesh-db
    env: postgres
    plan: starter
    databaseName: velocitymesh
    user: velocitymesh_user
    region: oregon

  # Redis Cache
  - type: redis
    name: velocitymesh-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru