apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocitymesh-backend-green
  namespace: velocitymesh-prod
  labels:
    app: velocitymesh-backend
    environment: green
    version: "{{IMAGE_TAG}}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: velocitymesh-backend
      environment: green
  template:
    metadata:
      labels:
        app: velocitymesh-backend
        environment: green
        version: "{{IMAGE_TAG}}"
    spec:
      containers:
      - name: backend
        image: ghcr.io/velocitymesh/backend:{{IMAGE_TAG}}
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: velocitymesh-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: velocitymesh-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: velocitymesh-secrets
              key: jwt-secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: velocitymesh-secrets
              key: stripe-secret-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: velocitymesh-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      serviceAccountName: velocitymesh-backend
      securityContext:
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: velocitymesh-backend
  namespace: velocitymesh-prod
  labels:
    app: velocitymesh-backend
spec:
  selector:
    app: velocitymesh-backend
    environment: green
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velocitymesh-backend
  namespace: velocitymesh-prod

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: velocitymesh-backend-hpa
  namespace: velocitymesh-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: velocitymesh-backend-green
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60